window.TOPICS = [
  {
    id: "cfs",
    title: "Cash flow statement",
    studio: "cfs",
    keys: "cash flow statement cfs as 3 as-3 as3 ind as 7 ias 7 asc 230 cashflow operating investing financing",
    ca: "CA Intermediate · Paper 1 Advanced Accounting · AS-3",
    cma: "US CMA Part 1 · External financial reporting (ASC 230)",
    blurb: "Explains why profit is not cash. Three columns: operating, investing, financing. CA Inter follows AS-3; CMA follows US GAAP.",
    notes: [
      "AS-3 (non-financial): interest paid = financing; interest & dividends received = investing; dividends paid = financing.",
      "US GAAP: interest paid/received and dividends received = operating; dividends paid = financing.",
      "Only cash moves. Plant bought by issue of shares is a note, not a flow.",
      "Cash equivalents: ≤ about 3 months, insignificant risk. A 2-year FD is investing.",
    ],
  },
  {
    id: "ratios",
    title: "Ratio analysis",
    keys: "ratio analysis liquidity current quick acid test solvency turnover profitability du pont roe roi financial statement analysis",
    ca: "CA Intermediate · Paper 6A Financial Management",
    cma: "US CMA Part 2 · Financial statement analysis",
    blurb: "Turn the three statements into questions: can we pay bills, are we geared, do we earn on capital?",
    notes: [
      "Liquidity: current ratio = CA/CL; quick ratio drops inventory and prepaid.",
      "Leverage: debt-equity, interest coverage. High gearing magnifies ROE and risk.",
      "Turnover: inventory, receivables, payables, capital employed — all are activity, not profitability.",
      "Profitability: gross margin, net margin, ROCE, ROE. DuPont: ROE = margin × asset turnover × equity multiplier.",
      "CMA loves common-size statements and trend analysis next to ratios. Never read one ratio alone.",
    ],
    flash: [
      { f: "Quick ratio", b: "(Current assets − inventory − prepaid) / current liabilities. Inventory is slow cash." },
      { f: "ROCE", b: "EBIT / capital employed. Tests operating return before financing mix." },
      { f: "Interest coverage", b: "EBIT / interest. Solvency of servicing debt from operations." },
    ],
    quiz: [
      { q: "Current ratio rises because inventory piled up. Liquidity is:", opts: ["Clearly better", "Maybe worse in cash terms", "Unchanged", "A financing inflow"], a: 1, explain: "Current ratio can look healthy while cash is trapped in stock. Pair with cash flow and quick ratio." },
      { q: "DuPont ROE is:", opts: ["EBIT/sales only", "Margin × turnover × leverage", "Current assets/current liabilities", "Cogs/average inventory"], a: 1, explain: "Net margin × asset turnover × equity multiplier. CMA staple." },
    ],
  },
  {
    id: "wc",
    title: "Working capital",
    keys: "working capital operating cycle cash conversion cycle receivables inventory payables miller orr",
    ca: "CA Intermediate · Paper 6A Financial Management",
    cma: "US CMA Part 2 · Corporate finance · working capital",
    blurb: "Gross WC is current assets. Net WC is CA − CL. The cycle is how many days cash is locked in operations.",
    notes: [
      "Operating cycle = inventory days + receivables days. Cash cycle = that minus payables days.",
      "Lengthening the cycle eats cash even if the P&L is green (same story as cash flow).",
      "Receivables: credit policy, factoring, ageing. Inventory: EOQ, safety stock. Payables: do not destroy supplier discount for vanity DPO.",
      "CMA: cash budget is the working-capital control document.",
    ],
    quiz: [
      { q: "Cash conversion cycle is:", opts: ["Inventory days only", "Inventory + receivables − payables days", "CA − CL", "PAT / equity"], a: 1, explain: "Days cash is stuck between paying suppliers and collecting customers." },
    ],
  },
  {
    id: "budget",
    title: "Budgeting and forecasting",
    keys: "budget master budget flexible budget cash budget zero based kaizen rolling forecast planning",
    ca: "CA Intermediate · Paper 4 Cost & Management Accounting",
    cma: "US CMA Part 1 · Planning, budgeting and forecasting",
    blurb: "A budget is a plan in numbers. A forecast is the latest unbiased estimate. CMA tests the difference hard.",
    notes: [
      "Master budget: sales → production → materials, labour, overhead → cash → budgeted statements.",
      "Flexible budget restates the plan at actual activity so variances are not just volume.",
      "ZBB starts at zero; incremental starts from last year. Rolling forecast drops a month and adds a month.",
      "CA costing paper wants functional budgets and cash budgets with workings.",
    ],
    quiz: [
      { q: "A flexible budget is prepared:", opts: ["Only at original volume", "At actual (or other) activity level", "After the audit report", "Only for cash"], a: 1, explain: "So you can split activity variance from spending/efficiency." },
    ],
  },
  {
    id: "marginal",
    title: "Marginal costing & CVP",
    keys: "marginal costing cvp break even contribution p/v ratio make or buy limiting factor variable costing",
    ca: "CA Intermediate · Paper 4 Cost & Management Accounting",
    cma: "US CMA Part 1 · Cost management; Part 2 · Decision analysis",
    blurb: "Contribution = sales − variable cost. Break-even is where contribution covers fixed cost.",
    notes: [
      "BEP (units) = Fixed cost / contribution per unit. P/V ratio = contribution / sales.",
      "Margin of safety = actual − BEP. Indifference point compares two cost structures.",
      "Limiting factor: rank by contribution per scarce resource, not per unit.",
      "Absorption vs marginal: fixed overhead in inventory vs period cost. CMA exam favourite.",
    ],
    quiz: [
      { q: "With a scarce machine hour, rank products by:", opts: ["Selling price", "Contribution per machine hour", "Total fixed cost", "Gross profit % only"], a: 1, explain: "Limiting-factor rule. Same logic in CMA decision analysis." },
    ],
  },
  {
    id: "standard",
    title: "Standard costing & variances",
    keys: "standard costing variance material labour overhead sales mix yield calendar",
    ca: "CA Intermediate · Paper 4 Cost & Management Accounting",
    cma: "US CMA Part 1 · Performance management",
    blurb: "Standard is the allowed cost. Variance is actual minus allowed, split by price/rate and usage/efficiency.",
    notes: [
      "Material: price (AQ × rate gap) and usage (qty gap × standard price).",
      "Labour: rate and efficiency. Idle time often a separate variance.",
      "Variable OH: spending and efficiency. Fixed OH: expenditure, volume, (sometimes) capacity/efficiency/calendar in CA.",
      "Sales: price and volume; mix and quantity when more than one product.",
    ],
    quiz: [
      { q: "Material usage variance uses:", opts: ["Actual price", "Standard price × qty gap", "Budgeted sales", "Fixed overhead rate"], a: 1, explain: "Quantity difference is priced at standard so price noise stays in the price variance." },
    ],
  },
  {
    id: "process",
    title: "Process costing",
    keys: "process costing equivalent units wip fifo weighted average abnormal loss scrap joint product by product",
    ca: "CA Intermediate · Paper 4 Cost & Management Accounting",
    cma: "US CMA Part 1 · Cost management",
    blurb: "Continuous production. Costs hug equivalent units. Abnormal loss is a period cost; normal loss is absorbed.",
    notes: [
      "EU: how many full units the WIP represents. FIFO and weighted average differ on opening WIP.",
      "Normal loss: expected; cost stays in good output (scrap credit if any).",
      "Abnormal loss/gain: valued like good output and shown separately.",
      "Joint products share cost up to split-off (physical / NRV). By-product is usually netted.",
    ],
    quiz: [
      { q: "Abnormal loss in process costing is:", opts: ["Ignored", "Valued like finished output and written off", "Always a cash outflow", "A financing item"], a: 1, explain: "It is unexpected, so it does not hide inside the good units." },
    ],
  },
  {
    id: "gst",
    title: "GST",
    keys: "gst goods and services tax cgst sgst igst itc supply reverse charge e way bill gstn",
    ca: "CA Intermediate · Paper 3B Taxation · GST",
    cma: "US CMA does not test Indian GST; map to ‘indirect tax awareness’ only",
    blurb: "Destination-based tax on supply. Intra-state = CGST+SGST. Inter-state = IGST. ITC is the engine.",
    notes: [
      "Charge: supply for consideration in the course of business, unless specifically exempt / out of scope.",
      "Time, value and place of supply decide when, how much, and which State.",
      "ITC blocked in 17(5) — remember motor cars (with exceptions), food, personal use.",
      "Returns and e-way bill are compliance, not optional memory.",
    ],
    quiz: [
      { q: "A Mumbai trader ships goods to Delhi. Levy is:", opts: ["CGST + SGST", "IGST", "Only SGST", "Only customs"], a: 1, explain: "Inter-state supply → IGST." },
    ],
  },
  {
    id: "itax",
    title: "Income-tax basics",
    keys: "income tax heads of income salary house property pgbp capital gains ifos deductions 80c tds advance tax",
    ca: "CA Intermediate · Paper 3A Income-tax law",
    cma: "US CMA uses US tax ideas only lightly; this is a CA paper",
    blurb: "Five heads, clubbing, set-off, deductions, then tax. Residential status decides the canvas.",
    notes: [
      "Resident and ordinarily resident: global income. NR: Indian income (with rules).",
      "Salary: old vs new regime is a computation choice. House property: NAV − municipal − 30% − interest.",
      "PGBP: books, depreciation, disallowances. Capital gains: STCG/LTCG and exemptions.",
      "TDS and advance tax are cash — they also show up in working-capital / CFS thinking.",
    ],
    quiz: [
      { q: "Standard deduction on house property (let out) is:", opts: ["100% of NAV", "30% of NAV", "Interest only", "Municipal tax only"], a: 1, explain: "Section 24(a): 30% of NAV after municipal taxes." },
    ],
  },
  {
    id: "audit",
    title: "Audit evidence & assertions",
    keys: "audit evidence sa 500 assertions vouching verification internal control risk inherent control detection",
    ca: "CA Intermediate · Paper 5 Auditing and Ethics",
    cma: "US CMA Part 1 · Internal controls",
    blurb: "Enough appropriate evidence for assertions: existence, completeness, valuation, rights, presentation.",
    notes: [
      "Risk = inherent × control. Detection risk is what the auditor sets with procedures.",
      "Vouching tests occurrence (books → source). Verification tests existence (asset → evidence).",
      "SA 315/330: understand the entity, respond to risks. SA 500: evidence. SA 230: documentation.",
      "CMA: COSO — control environment, risk assessment, control activities, information, monitoring.",
    ],
    quiz: [
      { q: "Vouching primarily tests:", opts: ["Completeness of unrecorded assets", "Occurrence of recorded transactions", "Going concern", "Subsequent events only"], a: 1, explain: "From the book back to the source document." },
    ],
  },
  {
    id: "coso",
    title: "Internal controls (COSO)",
    keys: "coso internal control sox segregation of duties preventive detective it general controls",
    ca: "CA Intermediate · Auditing (internal control chapter)",
    cma: "US CMA Part 1 · Internal controls (heavily tested)",
    blurb: "COSO cube: five components × three objectives (ops, reporting, compliance) × entity levels.",
    notes: [
      "Segregation: authorise, record, custody. Collusion beats it — monitoring matters.",
      "Preventive vs detective vs corrective. Automated vs manual.",
      "ITGC: access, change management, computer operations. Application controls sit on top.",
      "SOX 404 is US listed-company language CMA candidates still meet in the textbook.",
    ],
    quiz: [
      { q: "Bank reconciliation by someone with no cash custody is mainly:", opts: ["Preventive custody", "A detective control", "A financing activity", "Inherent risk"], a: 1, explain: "It finds what already went wrong. Dual custody over cash is preventive." },
    ],
  },
  {
    id: "ethics",
    title: "Professional ethics",
    keys: "ethics integrity objectivity independence confidentiality iesba ima statement ethical professional practice threats safeguards",
    ca: "CA Intermediate · Paper 5 Auditing and Ethics; ICAI Code",
    cma: "US CMA · IMA Statement of Ethical Professional Practice (both parts)",
    blurb: "CA: integrity, objectivity, professional competence, confidentiality, professional behaviour. CMA: IMA four standards plus resolution path.",
    notes: [
      "Threats: self-interest, self-review, advocacy, familiarity, intimidation.",
      "Safeguards: refuse the work, extra review, disclosure, exit the client.",
      "IMA path: follow company policy → higher authority → IMA ethics counsellor → resign as last resort. Do not go to the press first.",
      "Independence is for assurance. Confidentiality is not a cloak for illegal acts.",
    ],
    quiz: [
      { q: "First IMA ethics step when policy exists is:", opts: ["Call a journalist", "Follow the organisation’s established policy", "Post on LinkedIn", "Ignore it"], a: 1, explain: "IMA resolution: use internal channels first." },
    ],
  },
  {
    id: "tvm",
    title: "Time value of money",
    keys: "time value of money npv irr pv fv annuity perpetuity compounding discounting",
    ca: "CA Intermediate · Paper 6A Financial Management",
    cma: "US CMA Part 2 · Investment decisions / corporate finance",
    blurb: "A rupee today ≠ a rupee later. Discount at the opportunity cost of capital.",
    notes: [
      "PV = FV / (1+r)^n. Annuity tables for equal cash flows. Perpetuity = C/r.",
      "NPV: accept if > 0 at the hurdle rate. IRR: rate that sets NPV to zero.",
      "Conflict NPV vs IRR on mutually exclusive / non-normal cash flows: NPV wins for shareholder wealth.",
      "Nominal vs real rates; risk-adjusted discount rates.",
    ],
    quiz: [
      { q: "Mutually exclusive projects, NPV and IRR disagree. Prefer:", opts: ["Higher IRR always", "NPV at the cost of capital", "Payback", "Accounting rate of return"], a: 1, explain: "NPV measures wealth in today’s rupees." },
    ],
  },
  {
    id: "capbudg",
    title: "Capital budgeting",
    keys: "capital budgeting payback discounted payback profitability index sensitivity scenario real options",
    ca: "CA Intermediate · Paper 6A Financial Management",
    cma: "US CMA Part 2 · Investment decisions",
    blurb: "Long-life spend. Use incremental cash flows: tax shield on depreciation, ignore sunk cost, include opportunity cost.",
    notes: [
      "Initial outlay, life, WC recovered at end, tax, salvage.",
      "Payback ignores TVM and cash after cut-off. Discounted payback fixes TVM only.",
      "PI = PV inflows / PV outflows. Useful when capital is rationed.",
      "Sensitivity: one variable. Scenario: a story. Simulation: many draws. CMA territory.",
    ],
    quiz: [
      { q: "Sunk research cost in a project appraisal is:", opts: ["Added to outlay", "Ignored", "A financing inflow", "Always capitalised"], a: 1, explain: "Already spent. Incremental cash flows only." },
    ],
  },
  {
    id: "wacc",
    title: "Cost of capital & leverages",
    keys: "wacc cost of capital ke kd kp mm approach net income traditional leverage operating financial combined",
    ca: "CA Intermediate · Paper 6A Financial Management",
    cma: "US CMA Part 2 · Corporate finance",
    blurb: "WACC is the blended hurdle. Operating leverage is cost structure; financial leverage is debt.",
    notes: [
      "Ke: dividend discount / CAPM. Kd after tax = i(1−t). WACC uses market weights when asked.",
      "Trading on equity works only if ROCE > Kd.",
      "DOL = %ΔEBIT / %ΔSales. DFL = %ΔEPS / %ΔEBIT. DCL = DOL × DFL.",
      "MM with no tax: capital structure irrelevant. With tax: debt shield has value (until distress).",
    ],
    quiz: [
      { q: "After-tax cost of 10% debt, tax 30% is:", opts: ["10%", "7%", "13%", "3%"], a: 1, explain: "10 × (1−0.3) = 7%." },
    ],
  },
  {
    id: "as2",
    title: "Inventory (AS-2 / costing)",
    keys: "as 2 inventory valuation fifo weighted average nrv cost or nrv whichever is lower",
    ca: "CA Intermediate · Paper 1 Advanced Accounting · AS-2",
    cma: "US CMA Part 1 · Inventory (US GAAP lower of cost or NRV / market rules as taught)",
    blurb: "Inventory at cost or NRV, whichever is lower. Cost = costs to bring to present location and condition.",
    notes: [
      "Exclude abnormal waste, storage (unless production), selling costs, admin (unless specific).",
      "Formula: specific identification, FIFO, weighted average. LIFO is not AS-2.",
      "NRV = estimated selling price − completion − selling costs.",
      "Write-down is a period expense; reversal when NRV recovers (AS-2 allows).",
    ],
    quiz: [
      { q: "LIFO under AS-2 is:", opts: ["Preferred", "Not a permitted formula", "Mandatory for tax", "A cash equivalent"], a: 1, explain: "AS-2 permits specific ID, FIFO, weighted average — not LIFO." },
    ],
  },
  {
    id: "ppe",
    title: "PPE / depreciation",
    keys: "ppe fixed assets as 10 ind as 16 depreciation component accounting revaluation impairment",
    ca: "CA Intermediate · Paper 1 · AS-10 / Ind AS 16",
    cma: "US CMA Part 1 · PPE, depreciation methods",
    blurb: "Capitalise costs to bring the asset to working condition. Depreciate the depreciable amount over useful life.",
    notes: [
      "Component accounting: significant parts depreciated separately (Ind AS 16 / AS-10 revised).",
      "Methods: SLM, WDV. Change in method is change in estimate going forward (check the standard you are sitting).",
      "Revaluation: AS-10/Ind AS 16 revaluation model vs cost model. US GAAP generally cost.",
      "Subsequent spend: capital if it increases future benefit; else expense.",
    ],
    quiz: [
      { q: "A major engine replacement that extends life is usually:", opts: ["Always expense", "Capitalised and depreciated", "Financing cash", "Inventory"], a: 1, explain: "Future economic benefit increased — capital item." },
    ],
  },
  {
    id: "law",
    title: "Companies Act — directors & meetings",
    keys: "companies act 2013 directors board meeting agm quorum related party section 149 166 173",
    ca: "CA Intermediate · Paper 2 Corporate and Other Laws",
    cma: "US CMA uses US corporate governance, not the 2013 Act",
    blurb: "Who can be a director, how the board meets, duties in s.166, related-party guardrails.",
    notes: [
      "Minimum directors: public 3, private 2, OPC 1. At least one Indian-resident director.",
      "Board: first meeting in 30 days, then 4 meetings a year with ≤ 120 days gap (listed extras apply).",
      "Duties s.166: good faith, no conflict, no undue gain. Independent directors for prescribed classes.",
      "Always read the attempt’s ICAI module — penalties and exemptions move.",
    ],
    quiz: [
      { q: "Minimum directors in a public company:", opts: ["One", "Two", "Three", "Fifteen"], a: 2, explain: "Companies Act: public company minimum three directors." },
    ],
  },
  {
    id: "sm",
    title: "Strategic management",
    keys: "strategic management porter swot pest pestle balanced scorecard bcg ansoff mission vision",
    ca: "CA Intermediate · Paper 6B Strategic Management",
    cma: "US CMA Part 2 · Strategic planning flavour; BSC also in Part 1 performance",
    blurb: "Where to play and how to win. Tools: SWOT, Porter five forces, Ansoff, BCG, BSC.",
    notes: [
      "Mission is why we exist; vision is the picture of the future; strategy is the path.",
      "Porter: cost leadership, differentiation, focus. Five forces shape industry profit.",
      "BSC: financial, customer, internal process, learning & growth — not four random KPIs.",
      "BCG: star, cash cow, question mark, dog — based on share and market growth.",
    ],
    quiz: [
      { q: "Balanced scorecard’s four legs are:", opts: ["Only financial ratios", "Financial, customer, process, learning", "SWOT only", "Five forces"], a: 1, explain: "Kaplan & Norton. CMA performance favourite." },
    ],
  },
  {
    id: "fsa-cma",
    title: "US CMA financial reporting",
    keys: "us gaap income statement comprehensive income revenue recognition leases ifrs vs gaap cma part 1 reporting",
    ca: "Maps to CA Inter accounting, but US captions differ",
    cma: "US CMA Part 1 · External financial reporting decisions",
    blurb: "CMA Part 1 wants US GAAP recognition, measurement, and the statement set including OCI.",
    notes: [
      "Multi-step income statement; OCI for certain unrealised items (AFS under older lessons, pensions, FX translation, CF hedges).",
      "Revenue: control transfer (ASC 606 five steps) — similar story to Ind AS 115.",
      "Leases: ASC 842 almost all on-balance for lessees. Know operating vs finance presentation.",
      "Always contrast with AS/Ind AS when you sit both CA and CMA.",
    ],
    quiz: [
      { q: "ASC 606 revenue is recognised when:", opts: ["Cash is received always", "Control of the good/service transfers", "The contract is signed", "Inventory is purchased"], a: 1, explain: "Five-step model; control, not merely cash or signature." },
    ],
  },
  {
    id: "analytics",
    title: "Data analytics for CMA",
    keys: "data analytics big data descriptive diagnostic predictive prescriptive visualization cma technology",
    ca: "Useful overlap with audit sampling / MIS; not a full CA Inter paper",
    cma: "US CMA Part 1 · Technology and analytics",
    blurb: "Descriptive what happened, diagnostic why, predictive what next, prescriptive what to do.",
    notes: [
      "Volume, velocity, variety, veracity. Structured vs unstructured.",
      "Regression, clustering, decision trees at a conceptual level — CMA is not a coding paper.",
      "Controls over data: access, lineage, bias. Pretty dashboards with bad data still fail.",
      "Tie analytics to a decision (price, credit, fraud), not to a chart for its own sake.",
    ],
    quiz: [
      { q: "A model that recommends the order quantity is:", opts: ["Descriptive", "Prescriptive", "Only diagnostic", "A cash flow"], a: 1, explain: "Prescriptive = what action to take." },
    ],
  },
];
