window.TOPICS = [
  {
    id: "cfs",
    title: "Statement of cash flows",
    studio: "cfs",
    keys: "cash flow statement cfs asc 230 operating investing financing us gaap ifrs interest dividends",
    part: "Part 1 · A. External financial reporting (15%)",
    blurb: "US CMA uses US GAAP (ASC 230). Interest paid, interest received, and dividends received are operating. Dividends paid are financing.",
    notes: [
      "Three sections: operating, investing, financing. The statement must bridge opening cash to closing cash.",
      "US GAAP: interest paid, interest received, dividends received → operating. Dividends paid → financing.",
      "IFRS (IAS 7) lets firms classify interest/dividends in operating or investing/financing if they stay consistent — a GAAP vs IFRS exam favourite.",
      "Non-cash investing and financing (asset bought with stock) is disclosed, not forced into the three columns.",
    ],
  },
  {
    id: "stmts",
    title: "Financial statements",
    keys: "balance sheet income statement equity statement comprehensive income oci integrated reporting consolidated",
    part: "Part 1 · A. External financial reporting (15%)",
    blurb: "Know the four statements plus OCI, consolidations, and the idea of integrated reporting.",
    notes: [
      "Balance sheet: assets = liabilities + equity at a point in time.",
      "Income statement: performance for a period. Multi-step: gross profit → operating income → pretax → net.",
      "OCI holds certain unrealised items (translation, some hedges, pension adjustments) until recycled or reclassified as required.",
      "Consolidated statements combine parent and subsidiaries; NCI is equity, not a liability, under current US GAAP.",
    ],
    quiz: [
      {
        q: "Where do you report currency-translation adjustments for a foreign subsidiary (current-rate method)?",
        opts: ["Always net income", "Other comprehensive income (OCI)", "Financing cash flow", "Retained earnings only, never OCI"],
        a: 1,
        explain: "CTA sits in OCI / AOCI until the subsidiary is sold. It is not operating cash.",
      },
    ],
  },
  {
    id: "rev",
    title: "Revenue recognition (ASC 606)",
    keys: "revenue recognition asc 606 five steps control contract performance obligation ifrs 15",
    part: "Part 1 · A. Recognition, measurement, valuation",
    blurb: "Five steps: identify the contract, identify performance obligations, determine the price, allocate, recognise when control transfers.",
    notes: [
      "Control — not cash collection — drives timing.",
      "Multiple obligations in one contract: allocate the transaction price on relative standalone selling prices.",
      "Variable consideration is estimated (expected value or most likely) and constrained.",
      "IFRS 15 is very close; CMA still wants you to flag remaining GAAP/IFRS differences elsewhere (LIFO, development costs, etc.).",
    ],
    quiz: [
      {
        q: "When is revenue recognised under ASC 606?",
        opts: ["Always when cash arrives", "When the customer obtains control of the good or service", "When the contract is signed", "When inventory is purchased"],
        a: 1,
        explain: "Control transfer is the test. Cash can come earlier (contract liability) or later (receivable).",
      },
    ],
  },
  {
    id: "gaap-ifrs",
    title: "US GAAP vs IFRS",
    keys: "gaap ifrs differences lifo rd revaluation development costs extraordinary component",
    part: "Part 1 · A. Major differences between US GAAP and IFRS",
    blurb: "CMA tests headline differences, not every paragraph.",
    notes: [
      "Inventory: LIFO allowed under US GAAP, banned under IFRS.",
      "Development costs: US GAAP expenses R&D (with software exceptions); IFRS capitalises development when criteria are met.",
      "Revaluation of PPE: generally not US GAAP; allowed under IFRS.",
      "Cash flow: US GAAP locks interest paid into operating; IFRS allows a policy choice.",
    ],
    quiz: [
      {
        q: "Which inventory method is allowed under US GAAP but not under IFRS?",
        opts: ["FIFO", "Weighted average", "LIFO", "Specific identification"],
        a: 2,
        explain: "LIFO is a classic US GAAP vs IFRS difference. IFRS does not permit LIFO.",
      },
    ],
  },
  {
    id: "budget",
    title: "Planning, budgeting & forecasting",
    keys: "budget master flexible zero based rolling forecast regression learning curve expected value pro forma",
    part: "Part 1 · B. Planning, budgeting, and forecasting (20%)",
    blurb: "Biggest slice of Part 1. Master budget, flexible budget, ZBB, rolling forecast, regression, learning curves, expected value.",
    notes: [
      "Master budget: sales → production → purchases/labour/OH → cash → budgeted statements.",
      "Flexible budget restates the plan at actual activity so volume is not mixed with spending.",
      "Forecasting: simple/multiple regression, learning-curve (cumulative average vs incremental unit), expected value of scenarios.",
      "Top-level: pro forma income, projected BS, cash-flow projections.",
    ],
    quiz: [
      {
        q: "Why recast the budget at actual output (flexible budget)?",
        opts: [
          "To freeze original volume",
          "To compare actual cost with what cost should have been at that output",
          "Only for the external audit report",
          "It replaces the cash budget",
        ],
        a: 1,
        explain: "Then leftover gaps are spending or efficiency — not just ‘we made more units’.",
      },
    ],
  },
  {
    id: "standard",
    title: "Standard costing & variances",
    keys: "standard costing variance material labour overhead sales mix yield flexible budget",
    part: "Part 1 · C. Performance management (20%)",
    blurb: "Price/rate vs quantity/efficiency. Flexible-budget variances. Management by exception.",
    notes: [
      "Materials: price (AQ × rate gap) and usage (qty gap × standard price).",
      "Labour: rate and efficiency. Idle time is often separate.",
      "Variable OH: spending and efficiency. Fixed OH: budget (spending) and volume.",
      "Sales: price and volume; mix and quantity when there are several products.",
    ],
    quiz: [
      {
        q: "Material usage variance is valued at:",
        opts: ["Actual purchase price", "Standard price × quantity difference", "Budgeted sales", "Fixed overhead rate"],
        a: 1,
        explain: "Keep price noise in the price variance. Usage uses standard price.",
      },
    ],
  },
  {
    id: "perf",
    title: "ROI, residual income & balanced scorecard",
    keys: "roi residual income eva transfer pricing responsibility center kpi balanced scorecard",
    part: "Part 1 · C. Performance measures",
    blurb: "Responsibility centers, transfer prices, product/customer profitability, ROI vs RI, KPIs, BSC.",
    notes: [
      "ROI = operating income / invested capital. Can reject positive-NPV projects if ROI would fall.",
      "Residual income = operating income − (required rate × invested capital). Aligns better with NPV.",
      "Transfer pricing: market, cost-plus, negotiated. Goal congruence vs tax/customs.",
      "BSC: financial, customer, internal process, learning & growth.",
    ],
    quiz: [
      {
        q: "A manager rejects a project that earns 12% when the company hurdle is 10%, because unit ROI is 15% today. What measure would have accepted it?",
        opts: ["Higher current ROI", "Residual income (or EVA)", "Payback", "Current ratio"],
        a: 1,
        explain: "RI is positive when return beats the hurdle. ROI can create underinvestment.",
      },
    ],
  },
  {
    id: "costing",
    title: "Cost management & ABC",
    keys: "absorption variable direct costing abc job order life cycle joint byproduct overhead lean erp quality",
    part: "Part 1 · D. Cost management (15%)",
    blurb: "Cost behaviour, absorption vs variable, job/ABC/life-cycle, overhead, lean, cost of quality.",
    notes: [
      "Absorption puts fixed manufacturing OH into product cost (required for external US GAAP inventory).",
      "Variable (direct) costing expenses fixed OH as a period cost — used internally; CMA loves the income difference when inventory changes.",
      "ABC assigns OH by activities and cost drivers, not just DLH.",
      "Cost of quality: prevention, appraisal, internal failure, external failure.",
    ],
    quiz: [
      {
        q: "Inventory rises. Which method reports higher operating income?",
        opts: ["Variable costing", "Absorption costing", "They must be equal", "Cash basis"],
        a: 1,
        explain: "Absorption parks some fixed OH in the extra inventory. Variable costing expenses all fixed OH now.",
      },
    ],
  },
  {
    id: "coso",
    title: "Internal controls (COSO)",
    keys: "coso sox internal control segregation preventive detective itgc governance",
    part: "Part 1 · E. Internal controls (15%)",
    blurb: "COSO cube, SOX, segregation of duties, IT general and application controls, continuity.",
    notes: [
      "COSO: control environment, risk assessment, control activities, information & communication, monitoring.",
      "Objectives: operations, reporting, compliance.",
      "Preventive vs detective. Authorise / record / custody should be split.",
      "ITGC: access, change management, operations. Application controls sit on transactions.",
    ],
    quiz: [
      {
        q: "A person with no cash custody prepares the bank rec. This is mainly:",
        opts: ["Preventive", "Detective", "A financing cash flow", "Inherent risk"],
        a: 1,
        explain: "It finds what already happened. Dual custody over the cash box is preventive.",
      },
    ],
  },
  {
    id: "analytics",
    title: "Technology and analytics",
    keys: "data analytics descriptive diagnostic predictive prescriptive visualization erp sdlc data governance",
    part: "Part 1 · F. Technology and analytics (15%)",
    blurb: "AIS/ERP, data governance, SDLC, automation, BI, mining, four analytics types, visualisation.",
    notes: [
      "Descriptive what happened, diagnostic why, predictive what next, prescriptive what to do.",
      "Data governance: policies, lifecycle, access, breach controls.",
      "SDLC and process automation (RPA) show up as ‘finance transformation’.",
      "Pretty dashboards with bad data still fail — lineage and bias matter.",
    ],
    quiz: [
      {
        q: "Software that says ‘order 400 units now’ is:",
        opts: ["Descriptive", "Prescriptive", "Only diagnostic", "A cash-flow classification"],
        a: 1,
        explain: "Prescriptive recommends an action. Predictive would only forecast demand.",
      },
    ],
  },
  {
    id: "ratios",
    title: "Financial statement analysis",
    keys: "ratio analysis common size horizontal liquidity leverage activity profitability dupont market",
    part: "Part 2 · A. Financial statement analysis (20%)",
    blurb: "Common-size, trends, liquidity/leverage/activity/profitability/market ratios, earnings quality.",
    notes: [
      "Vertical (common-size) and horizontal (trend vs base year).",
      "Liquidity: current, quick, cash. Leverage: D/E, times interest earned, equity multiplier.",
      "Activity: inventory, receivables, payables, total asset turnover.",
      "DuPont: ROE = margin × turnover × leverage. Watch earnings quality (one-offs, aggressive revenue).",
    ],
    quiz: [
      {
        q: "Current ratio rose only because inventory piled up. Is liquidity really better?",
        opts: ["Yes — the ratio never lies", "Not necessarily — cash may be trapped in stock", "Yes, it is a financing inflow", "Inventory is not a current asset"],
        a: 1,
        explain: "Pair with the quick ratio and the cash flow statement. Stock is slow cash.",
      },
    ],
  },
  {
    id: "wc",
    title: "Working capital",
    keys: "working capital cash conversion cycle receivables inventory payables miller orr cash management",
    part: "Part 2 · B. Corporate finance · working capital",
    blurb: "CCC, credit policy, EOQ, payables, short-term credit, marketable securities.",
    notes: [
      "Cash conversion cycle = inventory days + receivable days − payable days.",
      "Longer CCC eats cash even if the income statement looks fine.",
      "Cash budget is the control document. Miller–Orr / Baumol are cash-balance models.",
      "Factoring, stretching payables, and lost discounts are exam calculations.",
    ],
    quiz: [
      {
        q: "Cash conversion cycle is:",
        opts: ["Inventory days only", "Inventory days + receivable days − payable days", "Current assets − current liabilities", "Net income / equity"],
        a: 1,
        explain: "How long cash is stuck between paying suppliers and collecting customers.",
      },
    ],
  },
  {
    id: "wacc",
    title: "WACC & cost of capital",
    keys: "wacc cost of capital capm dividend discount bond yield term structure ipo dividend policy lease",
    part: "Part 2 · B. Corporate finance (20%)",
    blurb: "Risk/return, CAPM, WACC, bond and stock valuation, raising capital, dividend policy, leases.",
    notes: [
      "Ke via CAPM: rf + β(rm − rf). Kd after tax = i(1 − t). WACC uses market weights.",
      "Bond value = PV of coupons + PV of face at YTM.",
      "Dividend policy and buybacks: signalling, tax, flotation costs.",
      "Lease vs buy is both a financing and a capital-budgeting cousin.",
    ],
    quiz: [
      {
        q: "Debt costs 10% before tax. Tax rate 30%. After-tax cost of debt is:",
        opts: ["10%", "7%", "13%", "3%"],
        a: 1,
        explain: "Interest is tax-deductible: 10% × (1 − 0.30) = 7%.",
      },
    ],
  },
  {
    id: "cvp",
    title: "CVP & short-term decisions",
    keys: "cvp break even contribution make or buy special order sell or process further add drop pricing target cost",
    part: "Part 2 · C. Business decision analysis (25%)",
    blurb: "Largest Part 2 weight. CVP, sunk vs opportunity cost, special orders, make/buy, pricing.",
    notes: [
      "BEP units = fixed cost / contribution per unit. P/V ratio = contribution / sales.",
      "Ignore sunk costs. Opportunity cost is a real cost of the next-best use.",
      "Special order: accept if incremental revenue > incremental cost (watch capacity).",
      "Target cost = market price − desired profit. Then design the product to that cost.",
    ],
    quiz: [
      {
        q: "Machine hours are scarce. Rank products by:",
        opts: ["Selling price", "Contribution per machine hour", "Total fixed cost", "Gross margin % only"],
        a: 1,
        explain: "Limiting-factor rule: contribution earned per unit of the scarce resource.",
      },
    ],
  },
  {
    id: "erm",
    title: "Enterprise risk management",
    keys: "enterprise risk management erm types of risk mitigation residual inherent hedge",
    part: "Part 2 · D. Enterprise risk management (10%)",
    blurb: "Identify, assess, mitigate, monitor. Inherent vs residual risk.",
    notes: [
      "Types: strategic, operational, financial, hazard/compliance.",
      "Responses: avoid, reduce, share/transfer (insurance, hedge), accept.",
      "Inherent risk before controls; residual after controls.",
      "ERM is entity-wide — not only the internal-control COSO cube from Part 1.",
    ],
    quiz: [
      {
        q: "Buying insurance for a warehouse fire is primarily:",
        opts: ["Risk avoidance", "Risk sharing / transfer", "Risk acceptance", "A detective control only"],
        a: 1,
        explain: "You still have the warehouse (not avoid). You transfer financial impact to the insurer.",
      },
    ],
  },
  {
    id: "capbudg",
    title: "Capital investment decisions",
    keys: "capital budgeting npv irr payback sensitivity incremental cash flow tax shield",
    part: "Part 2 · E. Capital investment decisions (10%)",
    blurb: "Incremental after-tax cash flows, NPV, IRR, payback, sensitivity.",
    notes: [
      "Include tax shield on depreciation, recover WC at the end, ignore sunk costs.",
      "NPV is the wealth measure. If NPV and IRR conflict on mutually exclusive projects, take NPV.",
      "Payback ignores TVM and cash after the cut-off (discounted payback fixes TVM only).",
      "Sensitivity: one input. Scenario: a story. Discount rate should match risk.",
    ],
    quiz: [
      {
        q: "Two projects, you can pick only one. NPV likes A, IRR likes B. Choose:",
        opts: ["Higher IRR always", "The project with higher NPV at the cost of capital", "Shorter payback", "Higher accounting rate of return"],
        a: 1,
        explain: "NPV is extra wealth in today’s dollars. That is the CMA default when they conflict.",
      },
    ],
  },
  {
    id: "ethics",
    title: "IMA ethics",
    keys: "ima statement ethical professional practice competence confidentiality integrity credibility fraud triangle",
    part: "Part 2 · F. Professional ethics (15%) — also appears in Part 1 overlays",
    blurb: "Four standards: competence, confidentiality, integrity, credibility. Then the resolution path.",
    notes: [
      "Follow the organisation’s policy first → immediate superior / next level (skip if involved) → IMA ethics counsel → resign. Do not go to the press first.",
      "Fraud triangle: pressure, opportunity, rationalisation.",
      "Integrity: mitigate conflicts, refuse gifts that bias judgment.",
      "Credibility: communicate fairly, disclose delays, constraints, and deficiencies.",
    ],
    quiz: [
      {
        q: "An ethics issue arises and the company has a written policy. First IMA step?",
        opts: ["Call a journalist", "Follow the organisation’s established policy", "Post on social media", "Ignore small amounts"],
        a: 1,
        explain: "Use internal channels first. Public disclosure is not step one.",
      },
    ],
  },
];
