window.CFS = {
  standards: {
    usgaap: {
      id: "usgaap",
      label: "US CMA · US GAAP",
      blurb: "Interest paid, interest received, and dividends received = operating. Dividends paid = financing. Overdrafts are usually financing.",
    },
    ifrs: {
      id: "ifrs",
      label: "IFRS (IAS 7) contrast",
      blurb: "CMA tests GAAP vs IFRS. IAS 7 allows interest and dividends in operating or investing/financing if the policy is consistent.",
    },
  },

  film: [
    {
      id: 0,
      set: "office",
      who: "Narrator",
      line: "Meridian Teas looks profitable. The P&L is green. The bank balance is not. You have one night to explain why cash vanished — before the board does.",
      note: "Profit is not cash. The cash flow statement is the only statement that starts with cash and ends with cash.",
      choices: [{ t: "Open the working papers", next: 1 }],
    },
    {
      id: 1,
      set: "office",
      who: "CFO · Meera Rao",
      line: "Net income is $480,000. Everyone wants a bonus. Treasury says payroll might bounce next week. Start with the three rivers of cash. Which one pays the lights?",
      note: "US GAAP (ASC 230) splits cash into operating, investing, and financing. That is the CMA Part 1 cash-flow map.",
      choices: [
        { t: "Operating activities — the core business", next: 2, ok: true, xp: 12, tip: "Correct. Day-to-day cash from customers, to suppliers, employees, and (usually) tax is operating." },
        { t: "Investing — buying the factory", next: 2, ok: false, xp: 0, tip: "Investing is long-term assets. Salaries and rent live in operating cash." },
        { t: "Financing — the bank loan", next: 2, ok: false, xp: 0, tip: "Financing is how we fund the firm. It is not how we run the tea rooms." },
      ],
    },
    {
      id: 2,
      set: "lab",
      who: "Audit intern · Kabir",
      line: "We bought a new roasting plant for $900,000. Half cash, half vendor credit. The intern booked the whole $900,000 as investing outflow. What actually hits the cash flow statement?",
      note: "Only cash moves. Non-cash investing/financing is disclosed separately — never forced into the three columns.",
      choices: [
        { t: "Investing outflow $900,000", next: 3, ok: false, xp: 0, tip: "Credit purchases are not cash. Only the $450,000 paid this year is an investing outflow. Disclose the rest as a non-cash note." },
        { t: "Investing outflow $450,000 + non-cash note for the rest", next: 3, ok: true, xp: 16, tip: "Cash paid = investing. The unpaid half is a significant non-cash investing/financing disclosure." },
        { t: "Operating outflow — it is a plant expense", next: 3, ok: false, xp: 0, tip: "A roasting plant is a capital asset. Expense vs capitalise is a P&L/BS question. Cash flow still treats the cash paid as investing." },
      ],
    },
    {
      id: 3,
      set: "bank",
      who: "Banker · Ms. Hale",
      line: "You drew a demand overdraft of $120,000 because collections slipped. Where does that live under US GAAP?",
      note: "US GAAP: bank overdrafts are generally financing liabilities, not cash. IFRS may net demand overdrafts in cash if they are cash management.",
      choices: [
        { t: "US GAAP: usually a financing liability, not cash", next: 4, ok: true, xp: 14, tip: "That is the CMA / US GAAP answer. IFRS (IAS 7) may include repayable-on-demand overdrafts in cash equivalents." },
        { t: "Always a cash equivalent, every framework", next: 4, ok: false, xp: 2, tip: "IFRS can treat some overdrafts as cash. US GAAP usually does not." },
        { t: "Operating inflow — we used it to pay suppliers", next: 4, ok: false, xp: 0, tip: "Purpose of spend does not reclassify the source." },
      ],
    },
    {
      id: 4,
      set: "bank",
      who: "CFO · Meera Rao",
      line: "Interest of $60,000 was paid on the term loan. Dividend of $40,000 was received on an equity investment. Classify them for the US CMA exam.",
      note: "US GAAP: interest paid, interest received, dividends received = operating. Dividends paid = financing. IFRS may classify interest/dividends differently if consistent.",
      choices: [
        { t: "US GAAP: both the interest paid and the dividend received are operating", next: 5, ok: true, xp: 18, tip: "That is the CMA default. IFRS is the contrast case, not the main US GAAP rule." },
        { t: "Interest paid is financing; dividend received is investing", next: 5, ok: false, xp: 4, tip: "That is an IFRS/old-Indian presentation, not US GAAP. CMA Part 1 wants operating for both." },
        { t: "Dividend received is financing", next: 5, ok: false, xp: 0, tip: "Dividends paid are financing. Dividends received are operating under US GAAP." },
      ],
    },
    {
      id: 5,
      set: "office",
      who: "Stores · Ananya",
      line: "Inventory jumped $220,000. Receivables jumped $150,000. Payables fell $80,000. Net income still looks pretty. What happened to operating cash?",
      note: "Indirect method: start with profit, then undo non-cash items and working-capital traps. Increases in current assets / decreases in current liabilities consume cash.",
      choices: [
        { t: "Operating cash is net income minus $450,000 of working-capital absorption", next: 6, ok: true, xp: 16, tip: "ΔInv 220 + ΔAR 150 + fall in AP 80 = $450,000 locked in operations." },
        { t: "Ignore WC — the cash flow statement only cares about cash at bank", next: 6, ok: false, xp: 0, tip: "WC is why the bank account disagrees with PAT. This is the whole point of the CFS." },
        { t: "Inventory increase is investing outflow", next: 6, ok: false, xp: 2, tip: "Inventory is operating working capital, not a capital asset (unless it is a capital WIP — it is not)." },
      ],
    },
    {
      id: 6,
      set: "board",
      who: "Chair · Board",
      line: "So we made profit, bought a plant, stuffed the warehouse, and paid the bank. Tell the board, in one line, what a cash flow statement is for.",
      note: "Exam gold: CFS explains the change in cash & cash equivalents by activity — not a second P&L.",
      choices: [
        { t: "It reconciles opening cash to closing cash by operating, investing and financing flows", next: 7, ok: true, xp: 20, tip: "That is the definition. Add non-cash investing/financing notes. US GAAP has no extraordinary-item heading." },
        { t: "It proves we are profitable", next: 7, ok: false, xp: 0, tip: "Profit is the P&L’s job. CFS can show a profitable company bleeding cash." },
        { t: "It replaces the balance sheet", next: 7, ok: false, xp: 0, tip: "The three statements talk to each other. CFS does not replace anything." },
      ],
    },
    {
      id: 7,
      set: "board",
      who: "Narrator",
      line: "Cut. Meridian still needs a rebuilt statement, a classification drill, and an exam gauntlet. That is the rest of the studio — same night, better marks.",
      note: "Play Sort, Lab, then Quiz. US GAAP is the CMA rule. The top-bar toggle is only to contrast IFRS.",
      choices: [{ t: "Leave the screening room", next: "hub" }],
    },
  ],

  chips: [
    { id: "c1", t: "Cash sales / collections from customers", usgaap: "op" },
    { id: "c2", t: "Wages and salaries paid", usgaap: "op" },
    { id: "c3", t: "Purchase of machinery (cash)", usgaap: "inv" },
    { id: "c4", t: "Proceeds from sale of patents", usgaap: "inv" },
    { id: "c5", t: "Proceeds from issue of equity shares", usgaap: "fin" },
    { id: "c6", t: "Redemption of preference shares", usgaap: "fin" },
    { id: "c7", t: "Interest paid on long-term borrowings", usgaap: "op", ifrs: "fin" },
    { id: "c8", t: "Interest received on investments", usgaap: "op", ifrs: "inv" },
    { id: "c9", t: "Dividend received on equity investments", usgaap: "op", ifrs: "inv" },
    { id: "c10", t: "Interim dividend paid on equity shares", usgaap: "fin" },
    { id: "c11", t: "Income tax paid (core profit)", usgaap: "op" },
    { id: "c12", t: "Refund of income tax received", usgaap: "op" },
    { id: "c13", t: "Rent received on property held as investment", usgaap: "inv" },
    { id: "c14", t: "Brokerage paid on purchase of investments", usgaap: "inv" },
    { id: "c15", t: "Underwriting commission paid on share issue", usgaap: "fin" },
    { id: "c16", t: "Loan to employees / advance to suppliers", usgaap: "op" },
    { id: "c17", t: "Loan to subsidiary + dividend from subsidiary", usgaap: "inv" },
    { id: "c18", t: "Bank deposit with 2-year maturity", usgaap: "inv" },
    { id: "c19", t: "Marketable securities (≤ 3 months, insignificant risk)", usgaap: "ceq" },
    { id: "c20", t: "Bank overdraft (demand)", usgaap: "fin", ifrs: "ceq" },
    { id: "c21", t: "Interest paid by a financial institution", usgaap: "op", ifrs: "op" },
    { id: "c22", t: "Taxes withheld on investment interest received", usgaap: "op", ifrs: "inv" },
    { id: "c23", t: "Insurance claim — loss of machinery by fire", usgaap: "inv" },
    { id: "c24", t: "Bad debts written off (no cash)", usgaap: "none" },
    { id: "c25", t: "Plant bought by issue of debentures (no cash)", usgaap: "none" },
    { id: "c26", t: "Cash withdrawn from current account into till", usgaap: "none" },
  ],

  labFacts: {
    pat: 48,
    dep: 10,
    gainVan: 2,
    intPaid: 6,
    taxPaid: 9,
    dInv: 22,
    dAr: 15,
    dAp: -8,
    plant: 45,
    van: 5,
    loan: 40,
    loanRepay: 12,
    divPaid: 8,
    intRec: 3,
    openCash: 18,
  },

  quiz: [
    {
      q: "A manufacturer pays interest on a bank loan. For the US CMA exam (US GAAP), where is interest paid classified?",
      opts: [
        "Operating activities",
        "Investing activities",
        "Financing activities",
        "Nowhere — interest is only an income-statement expense",
      ],
      a: 0,
      explain: "US GAAP (ASC 230) puts interest paid in operating. IFRS may classify it as financing. CMA wants the US GAAP answer unless the question says IFRS.",
    },
    {
      q: "Inventory rose by $220,000 this year. In the indirect method, what do you do to net income?",
      opts: [
        "Add $220,000 (treat stock as extra cash)",
        "Subtract $220,000 (cash is stuck in inventory)",
        "Show $220,000 as an investing outflow",
        "Ignore it because inventory is not cash in the bank",
      ],
      a: 1,
      explain: "An increase in current assets uses cash. Deduct it when bridging net income to cash from operations.",
    },
    {
      q: "The company buys a machine by issuing shares. No cash is paid. What appears in the three cash-flow sections?",
      opts: [
        "Investing outflow and financing inflow of the same amount",
        "Nothing — only a non-cash investing and financing disclosure",
        "Only a financing inflow",
        "Only an investing outflow",
      ],
      a: 1,
      explain: "Cash flow reports cash. Stock-for-asset deals are disclosed outside the three columns.",
    },
    {
      q: "Under US GAAP, dividends received on an equity investment are:",
      opts: ["Investing inflow", "Financing inflow", "Operating inflow", "Not a cash flow"],
      a: 2,
      explain: "US GAAP: dividends received (and interest received/paid) are operating. Dividends paid are financing.",
    },
    {
      q: "Opening cash is $180,000. Closing cash is $140,000. Net cash flow for the year is:",
      opts: ["$180,000 inflow", "$140,000 inflow", "$40,000 outflow", "Impossible to know without net income"],
      a: 2,
      explain: "Closing minus opening: 140 − 180 = $40,000 outflow. Net income is not required for this check.",
    },
    {
      q: "Why add depreciation back in the indirect method?",
      opts: [
        "Customers paid extra cash equal to depreciation",
        "It reduced net income but no cash left the bank",
        "It is an investing inflow",
        "US GAAP forbids showing depreciation",
      ],
      a: 1,
      explain: "Depreciation is a non-cash expense. Net income understates cash, so add it back.",
    },
    {
      q: "A van with book value $30,000 is sold for $50,000 cash. Net income includes a $20,000 gain. Indirect-method treatment?",
      opts: [
        "Add the gain in operating and ignore the $50,000",
        "Remove the $20,000 gain from operating; show $50,000 as investing inflow",
        "Show only the $20,000 as investing inflow",
        "Show $30,000 (book value) as investing inflow",
      ],
      a: 1,
      explain: "Take the gain out of operating or you double count. The cash that came in is $50,000 investing inflow.",
    },
    {
      q: "The board declares a dividend after year-end. It is not paid yet. This year’s cash flow statement shows:",
      opts: [
        "A financing outflow for the year just ended",
        "No outflow until the dividend is actually paid",
        "An operating outflow",
        "An investing outflow",
      ],
      a: 1,
      explain: "Cash flow follows cash. Unpaid dividends are not an outflow yet.",
    },
    {
      q: "Which identity must always hold?",
      opts: [
        "Net income equals cash from operations",
        "Opening cash + operating + investing + financing (+ FX on cash) = closing cash",
        "Investing cash equals depreciation",
        "Financing cash equals share capital",
      ],
      a: 1,
      explain: "The statement must explain the cash line on the balance sheet.",
    },
    {
      q: "Income taxes paid on ordinary profit are usually:",
      opts: ["Financing", "Investing", "Operating", "Omitted"],
      a: 2,
      explain: "US GAAP classifies income taxes paid as operating cash flows.",
    },
    {
      q: "US GAAP: interest paid and dividends received go to:",
      opts: ["Both operating", "Financing and investing", "Both investing", "Both financing"],
      a: 0,
      explain: "That is the CMA default. IFRS can put them elsewhere with a consistent policy.",
    },
    {
      q: "A 2-year bank certificate of deposit is:",
      opts: ["A cash equivalent", "An investing outflow (too long to be cash)", "Operating", "Not reported"],
      a: 1,
      explain: "Cash equivalents are short — generally three months or less from purchase — with insignificant risk.",
    },
    {
      q: "A euro bank account is restated at a higher dollar rate. No euros were converted. Is that a cash inflow?",
      opts: ["Operating inflow", "Investing inflow", "No — reconciling item, not a cash flow", "Financing inflow"],
      a: 2,
      explain: "Unrealised FX on cash held is shown as a reconciling line, separate from O/I/F.",
    },
    {
      q: "Cash paid to buy another company is:",
      opts: ["Operating", "Investing (do not net with a disposal of another unit)", "Financing", "A cash equivalent"],
      a: 1,
      explain: "Acquisitions and disposals are investing and are presented separately, not netted.",
    },
    {
      q: "Insurance pays cash for a machine destroyed by fire. Classification?",
      opts: ["Operating, because it is a claim", "Investing, because the machine was a long-term asset", "Financing", "Ignore it"],
      a: 1,
      explain: "Proceeds from PPE are investing. US GAAP does not use an ‘extraordinary item’ cash-flow heading.",
    },
    {
      q: "The indirect method:",
      opts: [
        "Adds every asset purchased",
        "Starts with net income, then adjusts non-cash items, working capital, and investing/financing items sitting in profit",
        "Omits depreciation",
        "Lists cash from customers (that is the direct method)",
      ],
      a: 1,
      explain: "Indirect = net income → cash from operations. Direct = gross receipts and payments. Both are allowed; CMA problems usually use indirect.",
    },
  ],

  flash: [
    { f: "Cash (US GAAP)", b: "Cash on hand and demand deposits." },
    { f: "Cash equivalents", b: "Short-term, highly liquid, readily convertible, insignificant risk — generally 3 months or less from purchase." },
    { f: "Movements inside cash / cash equivalents", b: "Not cash flows. Example: moving cash to a 60-day T-bill." },
    { f: "Operating (US GAAP)", b: "Core business. Includes interest paid, interest received, dividends received, and income taxes paid." },
    { f: "Investing", b: "Long-term assets and investments that are not cash equivalents." },
    { f: "Financing", b: "Owners and lenders: share issues, buybacks, debt drawdowns/repayments, dividends paid. Overdrafts usually sit here." },
    { f: "Interest: GAAP vs IFRS", b: "US GAAP: interest paid is operating. IFRS: operating or financing, consistently." },
    { f: "Dividends received", b: "US GAAP operating. IFRS operating or investing." },
    { f: "Non-cash investing/financing", b: "Disclose only: asset acquired for stock, conversion of debt to equity, lease commencement." },
    { f: "FX on cash held", b: "Not an operating/investing/financing flow. Separate reconciling item." },
    { f: "Indirect method", b: "Net income ± non-cash ± WC ± gains/losses whose cash is investing/financing." },
    { f: "CMA home", b: "Part 1 Section A — External financial reporting decisions, statement of cash flows." },
  ],

  resources: [
    { tag: "IMA", t: "CMA certification (official)", d: "Exam parts, windows, how to register.", href: "https://www.imanet.org/cma-certification" },
    { tag: "CSO", t: "2024 Content Specification Outline", d: "Weights for Part 1 and Part 2.", href: "https://www.imanet.org/-/media/IMA/Files/Home/IMA-Certifications/CMA-Certification/2024-CMA-Content-Specification-Outlines-Final.ashx" },
    { tag: "LOS", t: "2024 Learning Outcome Statements", d: "Detailed ‘candidate should be able to’ list.", href: "https://www.imanet.org/-/media/IMA/Files/Home/IMA-Certifications/CMA-Certification/2024-CMA-Learning-Outcome-Statement-Final.ashx" },
    { tag: "Handbook", t: "CMA Handbook", d: "MCQ + essay format and GAAP/IFRS policy.", href: "https://www.imanet.org/-/media/IMA/Files/Home/IMA-Certifications/CMA-Certification/CMA-Handbook-3132024.ashx" },
    { tag: "Ethics", t: "IMA Statement of Ethical Professional Practice", d: "Four standards and the resolution path.", href: "https://www.google.com/search?q=IMA+Statement+of+Ethical+Professional+Practice+PDF" },
    { tag: "FASB", t: "ASC 230 — Statement of Cash Flows", d: "US GAAP cash-flow classification.", href: "https://www.google.com/search?q=FASB+ASC+230+statement+of+cash+flows" },
    { tag: "COSO", t: "COSO Internal Control — Integrated Framework", d: "Part 1 internal controls backbone.", href: "https://www.google.com/search?q=COSO+internal+control+integrated+framework" },
    { tag: "COSO", t: "COSO ERM framework", d: "Part 2 enterprise risk management.", href: "https://www.google.com/search?q=COSO+ERM+framework+CMA" },
    { tag: "SEC", t: "SEC EDGAR", d: "How public companies present the item.", href: "https://www.sec.gov/edgar/search/" },
    { tag: "IFRS", t: "IAS 7 Statement of Cash Flows", d: "GAAP vs IFRS contrast for CMA.", href: "https://www.google.com/search?q=IAS+7+statement+of+cash+flows+IFRS" },
    { tag: "Practice", t: "US CMA MCQ search", d: "Practice items from review providers.", href: "https://www.google.com/search?q=US+CMA+multiple+choice+cash+flow" },
  ],
};
