window.CFS = {
  standards: {
    as3: {
      id: "as3",
      label: "CA Inter · AS-3",
      blurb: "Non-financial: interest paid = financing; interest & dividends received = investing; dividends paid = financing. Financial enterprise: interest paid/received and dividends received = operating.",
    },
    indas7: {
      id: "indas7",
      label: "Ind AS 7",
      blurb: "Same three activities. Demand overdrafts that are cash management sit in cash & cash equivalents. Interest/dividends: choose O or I/F and stay consistent. No extraordinary-item heading.",
    },
    usgaap: {
      id: "usgaap",
      label: "US CMA · US GAAP",
      blurb: "Interest paid/received and dividends received = operating. Dividends paid = financing. Overdrafts are usually financing, not cash.",
    },
  },

  film: [
    {
      id: 0,
      set: "office",
      who: "Narrator",
      line: "Meridian Teas looks profitable. The P&L is green. The bank balance is not. You have one night to explain why cash vanished — before the board does.",
      note: "Profit is not cash. The cash flow statement is the only statement that starts with cash and ends with cash.",
      choices: [{ t: "Open the working papers", next: 1 }],
    },
    {
      id: 1,
      set: "office",
      who: "CFO · Meera Rao",
      line: "PAT is ₹48 lakh. Everyone wants a bonus. Treasury says we cannot pay salaries next week. Start with the three rivers of cash. Which one pays the lights?",
      note: "AS-3 / Ind AS 7 / ASC 230 all split cash into Operating, Investing, Financing.",
      choices: [
        { t: "Operating activities — the core business", next: 2, ok: true, xp: 12, tip: "Correct. Day-to-day cash from customers, to suppliers, employees, and (usually) tax is operating." },
        { t: "Investing — buying the factory", next: 2, ok: false, xp: 0, tip: "Investing is long-term assets. Salaries and rent live in operating cash." },
        { t: "Financing — the bank loan", next: 2, ok: false, xp: 0, tip: "Financing is how we fund the firm. It is not how we run the tea rooms." },
      ],
    },
    {
      id: 2,
      set: "lab",
      who: "Audit intern · Kabir",
      line: "We bought a new roasting plant for ₹90 lakh. Half cash, half vendor credit. The intern booked the whole ₹90 lakh as investing outflow. What actually hits the cash flow statement?",
      note: "Only cash moves. Non-cash investing/financing is disclosed separately — never forced into the three columns.",
      choices: [
        { t: "Investing outflow ₹90 lakh", next: 3, ok: false, xp: 0, tip: "Credit purchases are not cash. Only the ₹45 lakh paid this year is an investing outflow. Disclose the ₹45 lakh vendor credit as a non-cash note." },
        { t: "Investing outflow ₹45 lakh + non-cash note for the rest", next: 3, ok: true, xp: 16, tip: "Textbook. Cash paid = investing. The unpaid half is a significant non-cash investing/financing disclosure." },
        { t: "Operating outflow — it is a plant expense", next: 3, ok: false, xp: 0, tip: "A roasting plant is a capital asset. Expense vs capitalise is a P&L/BS question. Cash flow still treats the cash paid as investing." },
      ],
    },
    {
      id: 3,
      set: "bank",
      who: "Banker · Ms. Hale",
      line: "You drew a demand overdraft of ₹12 lakh because collections slipped. Where does that live — cash, financing, or a nasty surprise?",
      note: "CA Inter RTP (AS-3 marking): bank overdraft and cash credit = financing. Ind AS 7: demand overdrafts that are part of cash management = cash & cash equivalents. US GAAP: usually financing.",
      choices: [
        { t: "CA Inter AS-3 exam: financing (Ind AS 7 may net in cash)", next: 4, ok: true, xp: 14, tip: "That is how ICAI Inter papers mark overdraft and cash credit. Ind AS 7 is the one that expressly puts repayable-on-demand overdrafts inside cash equivalents." },
        { t: "Always cash equivalent, every standard", next: 4, ok: false, xp: 2, tip: "Only Ind AS 7 / IAS 7 say that clearly. CA Inter AS-3 RTP treats overdraft as financing. US GAAP usually treats it as a liability / financing." },
        { t: "Operating inflow — we used it to pay suppliers", next: 4, ok: false, xp: 0, tip: "Purpose of spend does not reclassify the source." },
      ],
    },
    {
      id: 4,
      set: "bank",
      who: "CFO · Meera Rao",
      line: "Interest of ₹6 lakh was paid on the term loan. Dividend of ₹4 lakh was received on a trade investment. Classify them. Your standard toggle changes the answer — that is the CA vs CMA trap.",
      note: "AS-3: interest paid = financing; interest/dividend received = investing. US GAAP: interest paid, interest received, dividends received = operating. Dividends paid are financing everywhere.",
      choices: [
        { t: "I will classify per the selected standard, not by instinct", next: 5, ok: true, xp: 18, tip: "That discipline scores marks. Memorise the table, then apply the paper you are sitting." },
        { t: "Interest paid is always operating. Full stop.", next: 5, ok: false, xp: 4, tip: "True for US GAAP. False for AS-3. ICAI will punish this on CA Inter." },
        { t: "Dividend received is always financing", next: 5, ok: false, xp: 0, tip: "Dividends paid are financing. Dividends received are investing (AS-3) or operating (US GAAP)." },
      ],
    },
    {
      id: 5,
      set: "office",
      who: "Stores · Ananya",
      line: "Inventory jumped ₹22 lakh. Receivables jumped ₹15 lakh. Payables fell ₹8 lakh. PAT still looks pretty. What happened to operating cash?",
      note: "Indirect method: start with profit, then undo non-cash items and working-capital traps. Increases in CA / decreases in CL consume cash.",
      choices: [
        { t: "Operating cash is PAT minus ₹45 lakh of WC absorption", next: 6, ok: true, xp: 16, tip: "ΔInv +22 + ΔAR +15 + fall in AP 8 = ₹45 lakh locked in operations. Profitable firms die here." },
        { t: "Ignore WC — the cash flow statement only cares about cash at bank", next: 6, ok: false, xp: 0, tip: "WC is why the bank account disagrees with PAT. This is the whole point of the CFS." },
        { t: "Inventory increase is investing outflow", next: 6, ok: false, xp: 2, tip: "Inventory is operating working capital, not a capital asset (unless it is a capital WIP — it is not)." },
      ],
    },
    {
      id: 6,
      set: "board",
      who: "Chair · Board",
      line: "So we made profit, bought a plant, stuffed the warehouse, and paid the bank. Tell the board, in one line, what a cash flow statement is for.",
      note: "Exam gold: CFS explains the change in cash & cash equivalents by activity — not a second P&L.",
      choices: [
        { t: "It reconciles opening cash to closing cash by operating, investing and financing flows", next: 7, ok: true, xp: 20, tip: "That is the definition they want. Plus non-cash notes and (AS-3) extraordinary items if any." },
        { t: "It proves we are profitable", next: 7, ok: false, xp: 0, tip: "Profit is the P&L’s job. CFS can show a profitable company bleeding cash." },
        { t: "It replaces the balance sheet", next: 7, ok: false, xp: 0, tip: "The three statements talk to each other. CFS does not replace anything." },
      ],
    },
    {
      id: 7,
      set: "board",
      who: "Narrator",
      line: "Cut. Meridian still needs a rebuilt statement, a classification drill, and an exam gauntlet. That is the rest of the studio — same night, better marks.",
      note: "Play Sort, Lab, then Quiz. Toggle CA Inter vs US CMA on the top bar before you classify interest.",
      choices: [{ t: "Leave the screening room", next: "hub" }],
    },
  ],

  chips: [
    { id: "c1", t: "Cash sales / collections from customers", as3: "op", indas7: "op", usgaap: "op" },
    { id: "c2", t: "Wages and salaries paid", as3: "op", indas7: "op", usgaap: "op" },
    { id: "c3", t: "Purchase of machinery (cash)", as3: "inv", indas7: "inv", usgaap: "inv" },
    { id: "c4", t: "Proceeds from sale of patents", as3: "inv", indas7: "inv", usgaap: "inv" },
    { id: "c5", t: "Proceeds from issue of equity shares", as3: "fin", indas7: "fin", usgaap: "fin" },
    { id: "c6", t: "Redemption of preference shares", as3: "fin", indas7: "fin", usgaap: "fin" },
    { id: "c7", t: "Interest paid on long-term borrowings (non-financial co.)", as3: "fin", indas7: "fin", usgaap: "op" },
    { id: "c8", t: "Interest received on debentures held as investment", as3: "inv", indas7: "inv", usgaap: "op" },
    { id: "c9", t: "Dividend received on shares held as investments", as3: "inv", indas7: "inv", usgaap: "op" },
    { id: "c10", t: "Interim dividend paid on equity shares", as3: "fin", indas7: "fin", usgaap: "fin" },
    { id: "c11", t: "Income tax paid (core profit)", as3: "op", indas7: "op", usgaap: "op" },
    { id: "c12", t: "Refund of income tax received", as3: "op", indas7: "op", usgaap: "op" },
    { id: "c13", t: "Rent received on property held as investment", as3: "inv", indas7: "inv", usgaap: "inv" },
    { id: "c14", t: "Brokerage paid on purchase of investments", as3: "inv", indas7: "inv", usgaap: "inv" },
    { id: "c15", t: "Underwriting commission paid on share issue", as3: "fin", indas7: "fin", usgaap: "fin" },
    { id: "c16", t: "Loan to employees / advance to suppliers", as3: "op", indas7: "op", usgaap: "op" },
    { id: "c17", t: "Loan to subsidiary + dividend from subsidiary", as3: "inv", indas7: "inv", usgaap: "inv" },
    { id: "c18", t: "Bank deposit with 2-year maturity", as3: "inv", indas7: "inv", usgaap: "inv" },
    { id: "c19", t: "Marketable securities (≤ 3 months, insignificant risk)", as3: "ceq", indas7: "ceq", usgaap: "ceq" },
    { id: "c20", t: "Bank overdraft / cash credit (CA Inter marking)", as3: "fin", indas7: "ceq", usgaap: "fin" },
    { id: "c21", t: "Interest paid by a bank / financial enterprise", as3: "op", indas7: "op", usgaap: "op" },
    { id: "c22", t: "TDS on interest received from subsidiary", as3: "inv", indas7: "inv", usgaap: "op" },
    { id: "c23", t: "Insurance claim — loss of machinery by fire", as3: "inv", indas7: "inv", usgaap: "inv" },
    { id: "c24", t: "Bad debts written off (no cash)", as3: "none", indas7: "none", usgaap: "none" },
    { id: "c25", t: "Plant bought by issue of debentures (no cash)", as3: "none", indas7: "none", usgaap: "none" },
    { id: "c26", t: "Cash withdrawn from current account into till", as3: "none", indas7: "none", usgaap: "none" },
  ],

  labFacts: {
    pat: 48,
    dep: 10,
    gainVan: 2,
    intPaid: 6,
    taxPaid: 9,
    dInv: 22,
    dAr: 15,
    dAp: -8,
    plant: 45,
    van: 5,
    loan: 40,
    loanRepay: 12,
    divPaid: 8,
    intRec: 3,
    openCash: 18,
  },

  quiz: [
    {
      q: "Under AS-3, interest paid on a term loan is classified as:",
      opts: ["Operating outflow", "Investing outflow", "Financing outflow", "A non-cash note only"],
      a: 2,
      explain: "AS-3 treats interest paid as a financing outflow. US GAAP (ASC 230) puts interest paid in operating — the classic CA vs CMA split.",
    },
    {
      q: "Inventory increased by ₹22 lakh. In the indirect method this is:",
      opts: ["Added to profit (source of cash)", "Deducted from profit (use of cash)", "Investing outflow", "Ignored if it is finished goods"],
      a: 1,
      explain: "An increase in current assets absorbs cash. Deduct it from profit when bridging PAT to cash from operations.",
    },
    {
      q: "A company buys machinery by issuing equity shares. The cash flow statement shows:",
      opts: [
        "Investing outflow and financing inflow of the same amount",
        "Nothing in the three activities; disclose as non-cash investing/financing",
        "Only financing inflow",
        "Only investing outflow",
      ],
      a: 1,
      explain: "No cash moved. AS-3 / IAS 7 / US GAAP all require a separate note for significant non-cash investing and financing.",
    },
    {
      q: "US CMA (US GAAP): dividends received on an equity investment are:",
      opts: ["Investing inflow", "Financing inflow", "Operating inflow", "Not a cash flow"],
      a: 2,
      explain: "US GAAP parks dividends received (and interest received/paid) in operating. AS-3 parks dividends received in investing.",
    },
    {
      q: "Opening cash ₹18 lakh, closing cash ₹14 lakh. Net cash flow for the period is:",
      opts: ["₹18 lakh inflow", "₹14 lakh inflow", "₹4 lakh outflow", "Cannot say without PAT"],
      a: 2,
      explain: "CFS explains the change in cash & cash equivalents. 14 − 18 = (4). PAT is irrelevant to this identity.",
    },
    {
      q: "Depreciation of ₹10 lakh is added back in the indirect method because:",
      opts: [
        "It is a cash inflow from customers",
        "It reduced profit but did not use cash this year",
        "It is an investing inflow",
        "AS-3 forbids showing it",
      ],
      a: 1,
      explain: "Indirect method starts with accrual profit. Non-cash expenses (depreciation, amortisation, provisions) are added back.",
    },
    {
      q: "Gain on sale of a van ₹2 lakh (cash proceeds ₹5 lakh, book value ₹3 lakh). Correct CFS treatment (indirect):",
      opts: [
        "Add ₹2 lakh in operating; ignore the ₹5 lakh",
        "Deduct ₹2 lakh from operating; show ₹5 lakh as investing inflow",
        "Show ₹2 lakh as investing inflow only",
        "Show ₹3 lakh as investing inflow",
      ],
      a: 1,
      explain: "Strip the gain out of PAT (otherwise you double count). The full proceeds ₹5 lakh are an investing inflow.",
    },
    {
      q: "AS-3: proposed dividend declared after the balance sheet date but not paid:",
      opts: [
        "Financing outflow of the year just ended",
        "No cash flow this year — cash moves when paid",
        "Operating outflow",
        "Always a non-cash investing item",
      ],
      a: 1,
      explain: "Cash flow follows cash. Unpaid proposed dividend is not an outflow of the current year. It appears when actually paid (financing).",
    },
    {
      q: "Which identity must always hold?",
      opts: [
        "PAT = cash from operations",
        "Opening cash + net O/I/F flows = closing cash",
        "Investing cash = depreciation",
        "Financing cash = share capital",
      ],
      a: 1,
      explain: "The CFS is a bridge. If it does not reconcilie to the cash line on the balance sheet, the statement is wrong.",
    },
    {
      q: "Tax paid relating to core profit is usually:",
      opts: ["Financing", "Investing", "Operating (unless specifically identifiable with I/F)", "Never shown"],
      a: 2,
      explain: "AS-3 para 34: taxes on income are operating unless they can be specifically identified with financing or investing.",
    },
    {
      q: "AS-3 (non-financial enterprise): interest paid and dividends received are:",
      opts: ["Both operating", "Financing and investing respectively", "Both investing", "Both financing"],
      a: 1,
      explain: "AS-3 para 30. For a financial enterprise both interest paid and interest/dividends received are operating. Dividends paid are always financing.",
    },
    {
      q: "A 2-year fixed deposit with a bank is:",
      opts: ["Cash equivalent", "Operating", "Investing", "Not reported"],
      a: 2,
      explain: "Cash equivalents need short maturity — say three months or less from acquisition (AS-3 para 6). A two-year deposit is an investing outflow.",
    },
    {
      q: "Unrealised FX gain on a USD bank balance (no conversion happened):",
      opts: ["Operating inflow", "Investing inflow", "Not a cash flow; reconciling item to cash", "Financing inflow"],
      a: 2,
      explain: "AS-3 paras 25–27: unrealised exchange differences are not cash flows. Show the effect separately when reconciling opening to closing cash.",
    },
    {
      q: "Purchase of a business / subsidiary for cash is:",
      opts: ["Operating", "Investing (do not net with disposals)", "Financing", "Cash equivalent"],
      a: 1,
      explain: "AS-3 paras 37–39: acquisitions and disposals are investing, presented separately. You cannot net purchase of one unit against sale of another.",
    },
    {
      q: "Companies Act, 2013: who may skip a cash flow statement?",
      opts: ["Every listed company", "OPC, small company and dormant company (and some MSME non-companies)", "Every NBFC", "No one — CFS is always mandatory"],
      a: 1,
      explain: "Financial statements include a CFS, except OPC / small / dormant companies. AS-3 is also not mandatory for specified Level II–IV non-company MSMEs (they are encouraged).",
    },
    {
      q: "Insurance claim received for machinery destroyed by fire (AS-3):",
      opts: ["Operating only", "Investing, and (AS-3) as an extraordinary cash flow heading", "Financing", "Ignore — non-cash"],
      a: 1,
      explain: "The asset is investing. AS-3 paras 28–29 still want extraordinary cash flows classified into O/I/F and shown separately. Ind AS 7 drops the extraordinary heading.",
    },
    {
      q: "Indirect method starts with profit and then:",
      opts: [
        "Adds all assets purchased",
        "Adjusts non-cash items, WC changes, and items whose cash is investing/financing",
        "Ignores depreciation",
        "Reports gross receipts from customers",
      ],
      a: 1,
      explain: "AS-3 para 20. Direct method (para 18–19) instead shows gross receipts and payments. Both are allowed; listed Indian companies typically present indirect.",
    },
  ],

  flash: [
    { f: "AS-3: definition of cash", b: "Cash on hand and demand deposits with banks (para 5.1)." },
    { f: "AS-3: cash equivalents", b: "Short-term, highly liquid investments, readily convertible to known cash, insignificant risk. Normally maturity of three months or less from acquisition. Shares usually out, unless they are in-substance cash (e.g. preference shares acquired just before redemption)." },
    { f: "Movements inside cash / cash equivalents", b: "Not cash flows. Example: cash withdrawn from current account, 60-day T-bill bought with surplus cash." },
    { f: "Operating activities", b: "Principal revenue-producing activities and anything that is not investing or financing (para 5.4). Key indicator: can the business fund itself?" },
    { f: "Investing activities", b: "Acquisition and disposal of long-term assets and investments that are not cash equivalents (para 5.5)." },
    { f: "Financing activities", b: "Changes in size/composition of owners’ capital (including preference capital) and borrowings (para 5.6)." },
    { f: "Split a deferred-payment asset instalment", b: "Interest element → financing (non-financial). Principal / asset element → investing (para 10)." },
    { f: "Interest & dividends — non-financial (AS-3)", b: "Interest paid = financing. Interest received = investing. Dividends received = investing. Dividends paid = financing. Disclose each separately (para 30)." },
    { f: "Interest — financial enterprise (AS-3)", b: "Interest paid, interest received and dividends received = operating. Dividends paid still financing." },
    { f: "Taxes on income (AS-3 para 34)", b: "Separate disclosure. Operating unless specifically identified with investing or financing." },
    { f: "Non-cash investing/financing (para 40)", b: "Exclude from the statement; disclose elsewhere. Conversion of debt to equity, asset acquired by issue of shares, finance lease inception." },
    { f: "AS-3 vs Ind AS 7 headline diffs", b: "Ind AS 7: demand overdrafts in cash equivalents; no extraordinary items; extra acquisition/NCI disclosures; financing-liability reconciliation (44A); interest/dividend classification choice with consistency." },
  ],

  resources: [
    { tag: "AS-3 official", t: "ICAI AS 3 Cash Flow Statements", d: "Full standard: definitions, O/I/F examples, interest, tax, FX, non-cash, formats.", href: "https://indasaccess.icai.org/Volume-III/AS/asb.html?a=106" },
    { tag: "BoS lecture", t: "ICAI VCC — Cash Flow Statement", d: "Board of Studies classroom notes: cash vs cash equivalents, three activities, formats.", href: "https://live.icai.org/bos/vcc/pdf/Cash_Flow_Statement.pdf" },
    { tag: "BoS lecture", t: "ICAI VCC — Sanket Shah CFS class", d: "Same BoS topic pack used in virtual coaching.", href: "https://live.icai.org/bos/vcc/pdf/31032022_CA_Sanket_Shah_Cash_Flow_Statement_1648722691.pdf" },
    { tag: "Study material", t: "CA Intermediate Advanced Accounting (BoS)", d: "Paper 1 module that carries the CFS chapter. Use the edition ICAI lists for your attempt.", href: "https://www.icai.org/post/intermediate-course" },
    { tag: "Ind AS", t: "Ind AS 7 Statement of Cash Flows", d: "For companies on Ind AS. Know the AS-3 differences table before Group I.", href: "https://www.mca.gov.in/Ministry/pdf/INDAS7.pdf" },
    { tag: "Law", t: "Companies Act, 2013 — financial statements", d: "CFS is part of financial statements except OPC, small company, dormant company.", href: "https://www.mca.gov.in/Ministry/pdf/CompaniesAct2013.pdf" },
    { tag: "US CMA", t: "ASC 230 / CMA Part 1 — cash flows", d: "US GAAP classification (interest in operating). Pair with IMA Part 1 outlines.", href: "https://www.imanet.org/cma-certification" },
  ],
};
